server:
  port: 9003
spring:
  application:
    name: CLOUD-ALIBABA-PAYMENT
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
management:
  endpoint:
    web:
      exposure:
        include: '*'