server:
  port: 9001
spring:
  application:
    name: NACOS-CLIENT-PAYMENT
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
management:
  endpoint:
    web:
      exposure:
        include: '*'