server:
  port: 80
spring:
  application:
    name: CLOUD-CONSUMER-OPENFEIGN
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server02.com:7002/eureka,http://eureka-server01.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true
feign:
  client:
    config:
      default:
        ConnectTimeOut: 5000
        ReadTimeOut: 5000
logging:
  level:
    com.cloud.service.ConsumerService: debug
